apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "garmin-grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  INFLUXDB_USERNAME: {{ .Values.influxdb.auth.username | quote }}
  INFLUXDB_PASSWORD: {{ .Values.influxdb.auth.password | quote }}
  INFLUXDB_ADMIN_USER: {{ .Values.influxdb.auth.adminUser | quote }}
  INFLUXDB_ADMIN_PASSWORD: {{ .Values.influxdb.auth.adminPassword | quote }}
  GARMINCONNECT_EMAIL: {{ .Values.garmin.credentials.email | quote }}
  GARMINCONNECT_BASE64_PASSWORD: {{ .Values.garmin.credentials.base64Password | quote }}
