name: Build and Push Docker Image on Version Release

on:
  push:
    tags:
      - 'v*'  # matches version release only

env:
  IMAGE_NAME: garmin-fetch-data
  IMAGE_TAG: ${{ github.ref_name }}
  IMAGE_REPO: thisisarpanghosh

jobs:
  build_and_push:
    name: Build Multi-Arch Docker Image and Push to Docker Hub & GHCR
    if: ${{ github.repository == format('{0}/garmin-grafana', vars.IMAGE_REPO || 'arpanghosh8453') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io 
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for Multi-Architecture Support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Multi-Arch Image (linux/amd64, linux/arm64) and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.IMAGE_REPO || env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Build Helm Chart
        run: |
          cd k8s
          helm plugin install https://github.com/melmorabity/helm-kubeconform --version 0.6.4.1
          helm dependency build
          helm kubeconform --skip CustomResourceDefinition --summary .
          helm package . -d helm/charts --version ${{ env.IMAGE_TAG }}-helm
          helm repo index helm/charts --url https://${{ vars.IMAGE_REPO || env.IMAGE_REPO }}.github.io/garmin-grafana
          helm push helm/charts/garmin-grafana-${{ env.IMAGE_TAG }}-helm.tgz \
              oci://registry-1.docker.io/${{ vars.IMAGE_REPO || env.IMAGE_REPO }}
          helm push helm/charts/garmin-grafana-${{ env.IMAGE_TAG }}-helm.tgz \
              oci://ghcr.io/${{ github.repository_owner }}/